### ISSUE TITLE
次の修正をお願いします！

### ISSUE THREAD

**Issue by chii777** [calm0815/RallyComputer#2]
次の修正をお願いします！

- [x] 左上の穴位置修正  
  穴と7セグのクリアランスが狭い

- [x] 7セグとICの向きを揃える

- [x] 抵抗やコンデンサのピン幅？が広い→狭くする

- [x] 外部との接続ピンの説明をボード上に明記

_Originally posted by @calm0815 in https://github.com/calm0815/RallyComputer/pull/1#issuecomment-557514488_

**Comment by calm0815** [comment]
そうきたか笑
元のページ上でチェックしてもらってよかったのに笑
